[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.4.0"
dioxus-fullstack = "0.4.1"
tracing = "0.1.39"
tracing-subscriber = "0.3.17"
wasm-bindgen = "0.2.88"

[features]
default = []
ssr = ["dioxus-fullstack/axum"]
web = ["dioxus-fullstack/web"]
