build:
    dx build --features web

run $DIOXUS_ENV='{ "backend_url": "http://localhost:3000" }': build
    dx serve --features ssr --hot-reload --platform desktop

docker-build:
    cd .. && docker build . -f frontend/Dockerfile -t cochrane-frontend:dev

docker-run: docker-build
    docker run -it --network host -e DIOXUS_ENV='{ "backend_url": "http://localhost:3000" }' cochrane-frontend:dev
