set dotenv-load
set dotenv-filename := ".just-env"

build:
    cargo build

run:
    cargo run

docker-build:
    cd .. && docker build . -f backend/Dockerfile -t cochrane-backend:dev

docker-run: docker-build
    docker run -it --network host cochrane-backend:dev
