version: '3.1'

services:
  backend:
    build:
      context: ../
      dockerfile: backend/Dockerfile
    ports:
      - "8002:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE__HOST=postgres
      - DATABASE__PORT=5432
      - DATABASE__USERNAME=postgres
      - DATABASE__PASSWORD=example
      - DATABASE__DATABASE_NAME=cochrane
  frontend:
    build:
      context: ../
      dockerfile: frontend/Dockerfile
    ports:
      - "8001:8080"
    environment:
      - 'DIOXUS_ENV={ "backend_url": "http://localhost:8002" }'
  postgres:
    image: "postgres:16-alpine"
    restart: always
    ports:
      - "8101:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: cochrane
